# Generated by Django 3.1.3 on 2020-11-30 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salas',
            old_name='FK_TIPO_SALAS',
            new_name='FK_TIPO_SALA',
        ),
    ]
